name: deepskin-dev
channels:
  - default
  - anaconda
  - conda-forge

dependencies:
  # required
  - numpy>=1.15
  - python=3
  - pandas
  - scikit-learn
  - opencv-python
  - mahotas

  # documentation
  - nbsphinx
  - IPython
